# Generated by Django 3.2.3 on 2021-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0011_pago_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='Nombre',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Cliente', 'Cliente')], default='Cliente', max_length=30),
        ),
    ]
